language: java
install: true
sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build

before_deploy:
  - ./gradlew generateBintrayManifest

deploy:
  - provider: bintray
    file: plugin/build/bintray.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    dry-run: true

  - provider: releases
    api_key: $GITHUB_TOKEN
    file: 'plugin/build/libs/plugin-1.0-SNAPSHOT.jar'
    skip_cleanup: true
    on:
      tags: true

env:
  global:
  - secure: gG5ETnTOnwQg+D0YrMuQxFf5j/HFUIMWHvAKjdJP6uc3r1a/+mXFV1v9OEYHC/kzMVKujArNpgR4EkOoHvPMqqsnAzCrdFwP5dfbLxm3sia2NlOwPWBNzrAhMKIi/9Ziv0uSXuUXcezane5mvPSX9avE6HR+/yF1zfpHj2AWHLRfxwtRwflQrs9RTUZPntdxl2wBMgV0W2wgkwx/cdBAVKqSN1sASFqHF0oYpiFCFdW5R95CwdIj+7V0Y7cF1CnYnp8znTiQ+SuWYXYD+n7hLXJFia5yTIUoUPkd5LQ3vDZ4Rl26K25kfUkDvPHDVOWxjq0dSs61robyes6PJGO4vVzU8vpTDwMzuFp5Wbz0groazRhkY6/6qq3cLHBYM/KIVEH8boFgJ3JIcDPCcbKRRxD/TjTAuwE1COeP55C6Ky717F6A0rcIieuGue7d9HqyHNqNW32Bj5s3pDKn2E/ao3fgc4hYvviqr2nBkYzYljLx/xObWApZ0jYIMeXGS+supdbWKByYo3TAVP5a+ltfHg7jvDd3BX8kCJ3L+hpVQnACb+tn7W+CXIHqGRA3rhC/PZE0p4AT2fcWR4MQzF7E4/WuYbc1L/H03ntGE4WNsvHHoEr26EB96/UKF61UUzrS7olKQZ9TsKwkaBot7z6OufJNsXP7vu1pAnr3KsXIOa8=
  - secure: jvIBZz8f++nlLGEHMZS1RFjCdcmKUZ0BZCWLsyuaNavJz/a3UuvCBlmaXpmZftIwLlAzxii2BFcUSEjmq6p81AQInwzmVvd+MqGEtN/XKt7ETpLuN3JvnWj6CCYcXw7TK8zXTk6NX6T0aJP7smVePT7NbYCR4xkrgEN4LbegM1d6MIQB46eElzx3OKeVmct8Z5ejWyeLKmXynikvcVE2vY2Fa3i3nh7wP7vHusNG/TRbFf1pQTmltixzx+/u9LHD1gXDYcuxisjAxmuV6JVNOuL4fkS0CDX3X6nu7rMJpomxeTn1cvu96aaEGYcWcti0wCa9eB1QUeQmo0+QrvdsO9eOCbAhMi0feFOO36vGdAhWyaKNMkzkDiAtujmeTDpmtw/UvL0xM0UdruxiiI9HZia1tppXoqNvqfE4m5+ePDyAhhH6mVplTD6C7gGV9jepapHv1qtUZy/9hl+prYUZIkfp/XopSbTIvZLmwmZfVNVcuZ5OJ6bcwfPby98TwUiiEdit0oQm8/2g/U5Q6uA5/Erwkc6TzVY5AlILasYxtYIN5B+xq6sigt7rjAKQja9H/voBJr2rxi5odtA+IVSsldzNMGe6riLV5G3fdor+T7gO5CQA2qFDAgJa54Gm5K/uxWNGJvVmpNwLV+MH7GEADjEee9iiSgu9QJBsx5l5VLc=
  - secure: o9Pc/kIzlpAA72mH+OvG6DXyz3qJGE4wm+0v/SmkpVduN22v6Cx+5hom56Cc5/D3CT/aWI7cvDWDtipu7H+yKwMe1VKculceJuuW6xzMArdCXxTWZhobjR111yrNPXmyLeCYyvvWsuDvaTE6pFaLZ8Ybii2zEMteA+nF039yyOqBGyP9cqzRVswWZF/Fe+QBM+3JQFfI8QY8Wx5U9fz7sgWgIim4N0zYgnjglo2IUHxf/5mrq3fBOM+zbnuGXl0IQsdXf0ckC+F7gH9WWs5CGP6UfkysvQN18hZHD0wF8cCri0DmRb1vIrEhlhIAx8+Ga9nQtjIwDAIxntbujJHKOhbY5PXVaNIki9Sq9QGU1HoeQCpN/5qNSpp53cK6qNSCHPVN46YUZJKB9K6E5ROwPsXSRD4/PWwddJPm2PiHj3ed3zH8dJx5lJ7faTV6n0xWc9Eo3MqsgxaRZDvGv98yO3PDWiPSZJYCas/nSPw9K9lZqrWL1yVpAaTUvYf5QboBM58Ol9u48U/8TCLUo2rDv7GrGZ0zCRRCxxjqL6v2UUnwTPDmB5jFCUYv2+G8UuG+XyIv1T+00Ttu29ptFgGEsGFVTmkSHqgysxq+j68BeDoSY/k/dsrHPNJKvO7dTFr/+OZt8Y1V5Mh2DiNZ/LrlHwF1SnGeDSg/HN+t/Dojpuc=
